# Generated by Django 5.0.3 on 2024-10-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_holidayrecord_delete_holidayrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number_of_holidays_remaining',
            new_name='remaining_holidays',
        ),
    ]
