# Generated by Django 5.0.3 on 2024-10-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_number_of_holidays_remaining_customuser_remaining_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(),
        ),
    ]
