# Generated by Django 5.0.3 on 2024-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_attendancerecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
            
        ),
    ]
