# Generated by Django 5.0.3 on 2024-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_holidayrecord_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='remaining_holidays',
            new_name='remaining_holidays_current_year',
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_holidays',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
