# Generated by Django 5.0.3 on 2024-10-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_remaining_holidays_customuser_remaining_holidays_current_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='max_holidays',
            new_name='max_holidays_in_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remaining_holidays_current_year',
        ),
    ]
