# Generated by Django 5.0.3 on 2024-10-06 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_max_holidays_customuser_max_holidays_in_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrecord',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_checked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
