# Generated by Django 5.0.3 on 2024-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_holidayrecord_checked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrecord',
            name='checked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
