# Generated by Django 5.0.3 on 2024-11-29 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDTrainingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_title', models.TextField()),
                ('delivered_by', models.TextField()),
                ('delivery_of_course', models.CharField(choices=[('in_person', 'In-person'), ('online', 'Online')], max_length=20)),
                ('date_completed', models.DateField()),
                ('impact', models.TextField()),
                ('certificate_provided', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
