# Generated by Django 5.1.4 on 2026-10-08 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_cpdtraininglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdtraininglog',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpd_logs_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
