services:
  web:
    build: .
    restart: always
    command: gunicorn filemanagementDjango.wsgi:application --bind 0.0.0.0:8000 --workers 3
#    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - /etc/environment
    expose:
      - 8000
    ports:
      - "8000:8000"