# Generated by Django 5.1.4 on 2026-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Email sync state',
                'verbose_name_plural': 'Email sync state',
            },
        ),
    ]
