"""
Django settings for filemanagementDjango project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import socket
import sys
import logging.config
from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / 'filemanagementDjango' / '.env')
load_dotenv(BASE_DIR / '.env')


def require_env(name):
    """Return a required environment variable or fail fast.

    Secrets must come from the environment (or a .env file that is NOT
    committed) — there are deliberately no hardcoded fallbacks in this file,
    which is tracked in git.
    """
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(
            f"Required environment variable {name!r} is not set. "
            f"Set it in the environment or the (gitignored) .env file."
        )
    return value

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
try:
    LOGS_DIR.mkdir(exist_ok=True)
    # Set secure permissions (owner read/write, group/others read)
    os.chmod(LOGS_DIR, 0o755)
except OSError as e:
    import logging
    logging.error(f'Failed to create logs directory: {e}')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No hardcoded fallback — this file is tracked in git. Set SECRET_KEY via env/.env.
SECRET_KEY = require_env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Fails safe: defaults to False so a missing env var never enables DEBUG in prod.
# For local development, set DEBUG=True in your .env.
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Production: Set ALLOWED_HOSTS from environment variable or use specific domains
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]
else:
    # Fallback for development - restrict in production!
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'wip.anp.softwarised.com']
CSRF_TRUSTED_ORIGINS = [
    'https://wip.anp.softwarised.com',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'


SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 36000

# --- Security / HTTPS hardening ---------------------------------------------
# The app runs behind a TLS-terminating reverse proxy. Without this, Django
# thinks every request is plain HTTP, so Secure cookies and is_secure() break.
# Requires the proxy to set "X-Forwarded-Proto: https".
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies only over HTTPS in production (kept off in DEBUG so local dev works).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# NOTE: do NOT set CSRF_COOKIE_HTTPONLY — front-end AJAX reads the csrftoken
# cookie via getCookie('csrftoken') and sends it as the X-CSRFToken header.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Redirect HTTP->HTTPS at the app layer (proxy header above makes this safe).
SECURE_SSL_REDIRECT = not DEBUG

# HSTS: start conservative (1 hour) and ramp up once confirmed stable. Avoid
# enabling preload until HSTS has run cleanly for a while (hard to undo).
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = False

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# ---------------------------------------------------------------------------

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'file-management-django',
    }
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 2048

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filemanagementDjango',
    'users',
    'frontend',
    'backend',
    'django_quill',
    'django_crontab',
    'django.contrib.humanize',
    'compressor',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Views require login by default; opt out with @login_not_required.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # AxesMiddleware must be last so it sees the result of authentication.
    'axes.middleware.AxesMiddleware',
]

# django-axes brute-force protection. AxesStandaloneBackend must come first.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Disabled in local dev (DEBUG) so test logins can't lock you out and no axes
# migration/DB is needed locally; fully active in production.
AXES_ENABLED = not DEBUG
# Lock by USERNAME only — all staff share one office NAT IP, so locking by IP
# would lock out the whole office when one person mistypes their password.
AXES_LOCKOUT_PARAMETERS = [['username']]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_RESET_ON_SUCCESS = True
# Behind the proxy, derive the real client IP from X-Forwarded-For for accurate
# audit records (lockout itself is username-keyed, see above).
AXES_IPWARE_PROXY_COUNT = 1
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    'HTTP_X_FORWARDED_FOR',
    'REMOTE_ADDR',
]

ROOT_URLCONF = 'filemanagementDjango.urls'

AUTH_USER_MODEL = 'users.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.context_processors.matter_nav',
            ],
        },
    },
]


WSGI_APPLICATION = 'filemanagementDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'wip'),
        'USER': os.getenv('DB_USER', 'gb'),
        'PASSWORD': require_env('DB_USER_PASS'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': 'prefer',
        }

    }
}

# Check if PostgreSQL is available on the specified port


def is_postgresql_available(host, port):
    try:
        # Attempt to create a socket connection
        with socket.create_connection((host, port), timeout=1):
            return True
    except OSError:
        return False


# Check if PostgreSQL is available
if is_postgresql_available(DATABASES['default']['HOST'], DATABASES['default']['PORT']):
    try:
        import psycopg2
    except ImportError:
        # If PostgreSQL is not available, switch to SQLite
        DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'
        DATABASES['default']['NAME'] = os.path.join(BASE_DIR, 'db.sqlite3')
        DATABASES['default'].pop('OPTIONS', None)
else:
    # If PostgreSQL is not available on the specified port, switch to SQLite
    DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'
    DATABASES['default']['NAME'] = os.path.join(BASE_DIR, 'db.sqlite3')
    DATABASES['default'].pop('OPTIONS', None)


# ---- Client onboarding portal (separate internet-facing app) ----
# Base URL of the FastAPI portal backend, and the shared key the office uses to
# call its internal API. When ONBOARDING_PORTAL_BASE_URL is empty, the staff
# onboarding console runs against a built-in mock (no outbound portal calls), so
# it works before the portal is deployed. See
# plans/lets-plan-for-separate-bubbly-pony.md for the full design.
ONBOARDING_PORTAL_BASE_URL = os.getenv('ONBOARDING_PORTAL_BASE_URL', '')
ONBOARDING_PORTAL_API_KEY = os.getenv('ONBOARDING_PORTAL_API_KEY', '')
# Client-facing base URL the upload link points at (used to build the invite link).
ONBOARDING_PORTAL_PUBLIC_URL = os.getenv(
    'ONBOARDING_PORTAL_PUBLIC_URL', 'https://portal.anpsolicitors.com')

# Onboarding invite email, sent via Microsoft Graph (app-only) from this mailbox.
# Requires the Graph app registration to hold the Mail.Send application permission
# for this sender. When the credentials are unset, invites are still recorded but
# no email is sent (logged instead).
ONBOARDING_INVITE_FROM = os.getenv('ONBOARDING_INVITE_FROM', 'mail@anpsolicitors.com')
ONBOARDING_MAIL_CLIENT_ID = os.getenv(
    'ONBOARDING_MAIL_CLIENT_ID', os.getenv('AZURE_CLIENT_ID', ''))
ONBOARDING_MAIL_CLIENT_SECRET = os.getenv(
    'ONBOARDING_MAIL_CLIENT_SECRET', os.getenv('AZURE_CLIENT_SECRET', ''))
ONBOARDING_MAIL_TENANT_ID = os.getenv(
    'ONBOARDING_MAIL_TENANT_ID', os.getenv('AZURE_TENANT_ID', ''))
# Outbound invite emails are opt-in so test and development environments never
# email real people. Set ONBOARDING_SEND_INVITE_EMAILS=true in production. Invites
# still work without it: the link is kept on the case page for manual delivery.
ONBOARDING_SEND_INVITE_EMAILS = os.getenv(
    'ONBOARDING_SEND_INVITE_EMAILS', 'false').lower() in ('true', '1', 'yes')
if sys.argv[1:2] == ['test']:
    # Never email anyone from the test suite, whatever the environment says.
    ONBOARDING_SEND_INVITE_EMAILS = False

# Where the portal stores client uploads in SharePoint, so the office app can
# read them back ("Client copy" preview + convert-time copy). These MUST mirror
# the portal's own SHAREPOINT_ROOT / SHAREPOINT_TESTING / INTAKE_DRIVE_ID. The
# office reads with its existing (broader) SHAREPOINT_AZURE_* credential — see
# the Phase 0 setup guide. When ONBOARDING_INTAKE_DRIVE_ID is unset, the client
# copy falls back to the preview-mode placeholder.
ONBOARDING_INTAKE_DRIVE_ID = os.getenv('ONBOARDING_INTAKE_DRIVE_ID', '')
ONBOARDING_SHAREPOINT_ROOT = os.getenv('ONBOARDING_SHAREPOINT_ROOT', 'client_portal')
ONBOARDING_SHAREPOINT_TESTING = os.getenv(
    'ONBOARDING_SHAREPOINT_TESTING', 'true').lower() in ('true', '1', 'yes')


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True

DATE_INPUT_FORMATS = ('%d-%m-%Y', '%Y-%m-%d')

DATE_FORMAT = '%d/%m/%Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SharePoint storage (see plan: dedicated Azure app + four document libraries)
USE_SHAREPOINT = os.getenv('USE_SHAREPOINT', 'False').lower() in ('true', '1', 'yes')
SHAREPOINT_AZURE_CLIENT_ID = os.getenv('SHAREPOINT_AZURE_CLIENT_ID', '')
SHAREPOINT_AZURE_CLIENT_SECRET = os.getenv('SHAREPOINT_AZURE_CLIENT_SECRET', '')
SHAREPOINT_AZURE_TENANT_ID = os.getenv('SHAREPOINT_AZURE_TENANT_ID', '')
SHAREPOINT_SITE_ID = os.getenv('SHAREPOINT_SITE_ID', '')
SHAREPOINT_DRIVE_IDS = os.getenv(
    'SHAREPOINT_DRIVE_IDS',
    '{"Undertakings":"","StaffDocuments":"","BundleSources":"","BundleFinal":""}',
)
BUNDLE_SHARE_LINK_EXPIRY_DAYS = int(os.getenv('BUNDLE_SHARE_LINK_EXPIRY_DAYS', '30'))
BUNDLE_SHARE_LINK_USE_PASSWORD = os.getenv(
    'BUNDLE_SHARE_LINK_USE_PASSWORD', 'true'
).lower() in ('true', '1', 'yes')
BUNDLE_SHARE_LINK_SCOPE = os.getenv('BUNDLE_SHARE_LINK_SCOPE', 'anonymous').strip().lower()

if USE_SHAREPOINT:
    STORAGES = {
        'default': {
            'BACKEND': 'backend.storage.sharepoint.SharePointStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': MEDIA_ROOT,
                'base_url': MEDIA_URL,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRONJOBS = [
    ('*/15 * * * *', 'email_sorting.utils.get_emails_and_store',
     '>>'+str(LOGS_DIR)+'/email_job.log 2>&1'),
    ('* * 15 * *', 'email_sorting.utils.remove_log_file',
     '>>'+str(LOGS_DIR)+'/remove_log.log 2>&1'),
    # Office hours only (07:00–18:xx). The first run each morning does a full
    # catch-up scan for the overnight gap, so nothing is missed.
    ('*/15 7-18 * * *', 'backend.granola.cron.sync_granola_notes',
     '>>'+str(LOGS_DIR)+'/granola_job.log 2>&1'),
]

# Central Granola API key. Prefer setting this via the environment; falls back
# to the GranolaConfig row in the database when unset.
GRANOLA_API_KEY = os.environ.get('GRANOLA_API_KEY', '')

QUILL_CONFIGS = {
    'default': {
        'theme': 'snow',
        'modules': {
            'syntax': True,
            'toolbar': [
                [
                    {'font': []},
                    {'header': []},
                    {'align': []},
                    'bold', 'italic', 'underline', 'strike', 'blockquote',
                    {'color': []},
                    {'background': []},
                ],

                [{'list': 'ordered'}, {'list': 'bullet'}],

            ]
        }
    }
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {pathname}:{lineno} {funcName} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'django_file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'mode': 'a',
        },
        'application_file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'application.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
            'mode': 'a',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'detailed',
            'mode': 'a',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'detailed',
            'mode': 'a',
        },
        'email_file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'email.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
            'mode': 'a',
        },
        'gunicorn_file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'gunicorn.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'mode': 'a',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['django_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gunicorn.error': {
            'handlers': ['gunicorn_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gunicorn.access': {
            'handlers': ['gunicorn_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Application loggers
        'backend': {
            'handlers': ['application_file', 'error_file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'backend.bundle_pdf': {
            'handlers': ['application_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['application_file', 'error_file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'frontend': {
            'handlers': ['application_file', 'error_file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'email_sorting': {
            'handlers': ['email_file', 'error_file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # Noisy third-party libraries — keep files, hide from console
        'azure': {
            'handlers': ['application_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpx': {
            'handlers': ['application_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'httpcore': {
            'handlers': ['application_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'msal': {
            'handlers': ['application_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['application_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Root logger
        '': {
            'handlers': ['console', 'application_file', 'error_file'],
            'level': 'INFO',
        },
    },
}
