# Generated by Django 5.0.3 on 2024-07-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_free30minsattendees_free30mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free30minsattendees',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='free30minsattendees',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='free30minsattendees',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='free30minsattendees',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
