# Generated by Django 5.0.3 on 2024-07-19 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_free30minsattendees_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='free30mins',
            name='fee_earner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free30_mins_fee_earner', to=settings.AUTH_USER_MODEL),
        ),
    ]
