# Generated by Django 5.0.3 on 2024-08-20 10:09

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_free30mins_fee_earner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Undertaking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_given', models.DateField()),
                ('given_to', models.TextField()),
                ('description', models.TextField()),
                ('document_given_on', models.FileField(upload_to=backend.models.undertaking_file_upload_path)),
                ('date_discharged', models.DateField()),
                ('discharged_proof', models.FileField(upload_to=backend.models.undertaking_file_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undertaking_created_by', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.wip')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undertaking_given_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
