# Generated by Django 5.0.3 on 2024-09-05 11:56

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_undertaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undertaking',
            name='date_discharged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='undertaking',
            name='discharged_proof',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.undertaking_file_upload_path),
        ),
    ]
