# Generated by Django 5.0.3 on 2024-09-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_undertaking_discharged_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wip',
            name='undertakings',
        ),
    ]
