# Generated by Django 5.0.3 on 2024-10-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_policies_attendancerecord_holidayrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='holidayrequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sicknessrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sicknessrecord',
            name='employee',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='HolidayRequest',
        ),
        migrations.DeleteModel(
            name='SicknessRecord',
        ),
    ]
