# Generated by Django 5.0.3 on 2024-10-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_notification_policy_policyversion_delete_policies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policiesread',
            name='policy_number',
        ),
        migrations.AddField(
            model_name='policiesread',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='backend.policy'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
