# Generated by Django 5.0.3 on 2024-10-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_policiesread_policy_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policiesread',
            name='policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_versions', to='backend.policyversion'),
        ),
    ]
