# Generated by Django 5.0.3 on 2024-11-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_policiesread_policy_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterattendancenotes',
            name='is_charged',
            field=models.BooleanField(default=True),
        ),
    ]
