# Generated by Django 5.1.4 on 2025-09-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_bundle_bundlesection_bundledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextwork',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='to_do', max_length=20),
        ),
    ]
