# Generated by Django 5.1.4 on 2025-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_nextwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextwork',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
