# Generated by Django 5.1.4 on 2026-02-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_nextwork_urgency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('F', 'Final'), ('R', 'Rejected')], default='P', max_length=1)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_created_by', to=settings.AUTH_USER_MODEL)),
                ('file_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='backend.wip')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='backend.invoices')),
            ],
        ),
    ]
