# Generated by Django 5.1.4 on 2026-02-11 00:00

import ast
import json
from decimal import Decimal
from django.db import migrations, models


CURRENT_VAT_RATE = Decimal('0.20')


def _parse_costs(raw_costs):
    if isinstance(raw_costs, list):
        return raw_costs

    parsed = None
    if isinstance(raw_costs, str):
        for parser in (json.loads, ast.literal_eval):
            try:
                parsed = parser(raw_costs)
                break
            except Exception:
                continue
    elif isinstance(raw_costs, (tuple, set)):
        parsed = list(raw_costs)

    if isinstance(parsed, list):
        return parsed
    return []


def populate_invoice_vat(apps, schema_editor):
    Invoice = apps.get_model('backend', 'Invoices')
    for invoice in Invoice.objects.all().iterator():
        costs = _parse_costs(invoice.our_costs)
        total_costs = Decimal('0')
        for cost in costs:
            try:
                total_costs += Decimal(str(cost))
            except Exception:
                continue
        invoice.vat = round(total_costs * CURRENT_VAT_RATE, 2)
        invoice.save(update_fields=['vat'])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.RunPython(populate_invoice_vat, migrations.RunPython.noop),
    ]
