# Generated by Django 5.1.4 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_invoices_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='vat_calculation_mode',
            field=models.CharField(
                blank=True,
                choices=[('auto', 'Auto'), ('manual', 'Manual')],
                default='auto',
                max_length=10,
            ),
        ),
    ]
