# Generated by Django 5.1.4 on 2026-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_pricingitem_vat_treatment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='free30mins',
            index=models.Index(fields=['-date', '-start_time', '-id'], name='free30mins_latest_idx'),
        ),
    ]
