# Generated by Django 5.1.4 on 2026-05-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_free30mins_latest_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientKeyDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('proof_of_id', 'Proof of ID'), ('proof_of_address', 'Proof of Address')], max_length=50)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('document_reference', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_documents', to='backend.clientcontactdetails')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_client_key_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
