# Generated by Django 5.1.4 on 2026-05-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_client_key_document_expiry_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterKeyDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_type', models.CharField(choices=[('hearing', 'Hearing'), ('meeting', 'Meeting'), ('conference', 'Conference'), ('mediation', 'Mediation'), ('deadline', 'Deadline'), ('appointment', 'Appointment'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matter_key_dates_created_by', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_dates', to='backend.wip')),
            ],
            options={
                'ordering': ['date', 'time', 'title'],
            },
        ),
    ]
