# Generated by Django 5.1.4 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_matter_key_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='modifications',
            index=models.Index(fields=['content_type', 'object_id'], name='modifications_obj_idx'),
        ),
    ]
