# Generated by Codex on 2026-05-19

from django.db import migrations, models
from django.db.models import F


def backfill_client_compliance(apps, schema_editor):
    WIP = apps.get_model('backend', 'WIP')
    RiskAssessment = apps.get_model('backend', 'RiskAssessment')
    ClientContactDetails = apps.get_model('backend', 'ClientContactDetails')
    AuthorisedParties = apps.get_model('backend', 'AuthorisedParties')

    AuthorisedParties.objects.filter(
        date_of_last_aml__isnull=True,
        date_of_id_check__isnull=False,
    ).update(date_of_last_aml=F('date_of_id_check'))

    client_updates = {}

    for matter in WIP.objects.all().only(
        'client1_id',
        'client2_id',
        'terms_of_engagement_client1',
        'terms_of_engagement_client2',
        'ncba_client1',
        'ncba_client2',
    ):
        if matter.client1_id:
            values = client_updates.setdefault(matter.client1_id, {
                'terms_of_engagement_signed': False,
                'ncba_signed': False,
                'pep_signed': False,
                'source_of_funds_signed': False,
            })
            values['terms_of_engagement_signed'] |= bool(matter.terms_of_engagement_client1)
            values['ncba_signed'] |= bool(matter.ncba_client1)

        if matter.client2_id:
            values = client_updates.setdefault(matter.client2_id, {
                'terms_of_engagement_signed': False,
                'ncba_signed': False,
                'pep_signed': False,
                'source_of_funds_signed': False,
            })
            values['terms_of_engagement_signed'] |= bool(matter.terms_of_engagement_client2)
            values['ncba_signed'] |= bool(matter.ncba_client2)

    for assessment in RiskAssessment.objects.select_related('matter').only(
        'matter_id',
        'matter__client1_id',
        'matter__client2_id',
        'is_pep_questionnaire_completed',
        'is_source_of_funds_questionnaire_completed',
    ):
        matter = assessment.matter
        if not matter:
            continue

        client_ids = [matter.client1_id]
        if matter.client2_id:
            client_ids.append(matter.client2_id)

        for client_id in client_ids:
            if not client_id:
                continue
            values = client_updates.setdefault(client_id, {
                'terms_of_engagement_signed': False,
                'ncba_signed': False,
                'pep_signed': False,
                'source_of_funds_signed': False,
            })
            values['pep_signed'] |= assessment.is_pep_questionnaire_completed == 'Yes'
            values['source_of_funds_signed'] |= assessment.is_source_of_funds_questionnaire_completed == 'Yes'

    for client_id, values in client_updates.items():
        update_values = {
            field: True
            for field, value in values.items()
            if value
        }
        if update_values:
            ClientContactDetails.objects.filter(id=client_id).update(**update_values)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_modifications_object_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorisedparties',
            name='date_of_last_aml',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcontactdetails',
            name='ncba_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientcontactdetails',
            name='pep_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientcontactdetails',
            name='source_of_funds_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientcontactdetails',
            name='terms_of_engagement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wip',
            name='zdrive_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='authorisedparties',
            name='date_of_id_check',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_client_compliance, migrations.RunPython.noop),
    ]
