# Generated by Codex on 2026-05-29

import secrets

from django.db import migrations, models


def populate_bundle_share_codes(apps, schema_editor):
    Bundle = apps.get_model('backend', 'Bundle')
    for bundle in Bundle.objects.filter(share_code__isnull=True):
        while True:
            share_code = secrets.token_urlsafe(12)
            if not Bundle.objects.filter(share_code=share_code).exists():
                bundle.share_code = share_code
                bundle.save(update_fields=['share_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_clientcontactdetails_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='share_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(populate_bundle_share_codes, migrations.RunPython.noop),
    ]
