# Generated by Django 5.1.4 on 2026-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_bundle_share_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterfilereview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
