# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_matterfilereview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundledocument',
            name='page_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
