# Generated by Django 5.1.4 on 2026-05-30 11:40

import backend.sharepoint.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_bundle_and_document_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to=backend.sharepoint.paths.bundle_final_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='bundledocument',
            name='file',
            field=models.FileField(upload_to=backend.sharepoint.paths.bundle_document_upload_path),
        ),
    ]
