# Generated by Django 5.1.4 on 2026-05-30 14:20

import backend.sharepoint.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_sharepoint_upload_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='final_pdf',
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=backend.sharepoint.paths.bundle_final_pdf_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name='bundledocument',
            name='file',
            field=models.FileField(
                max_length=255,
                upload_to=backend.sharepoint.paths.bundle_document_upload_path,
            ),
        ),
    ]
