# Generated by Django 5.1.4 on 2026-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_bundle_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlesection',
            name='date_sort',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual order'),
                    ('date_asc', 'Date (oldest first)'),
                    ('date_desc', 'Date (newest first)'),
                ],
                default='manual',
                max_length=16,
            ),
        ),
    ]
