# Generated by Django 5.1.4 on 2026-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_bundlesection_date_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlesection',
            name='date_sort',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual order'),
                    ('date_asc', 'Date (oldest first)'),
                    ('date_desc', 'Date (newest first)'),
                ],
                default='date_asc',
                max_length=16,
            ),
        ),
    ]
