# Generated by Django 5.1.4 on 2026-05-31

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_bundle_court_hearing_lines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(
                    choices=[('interim', 'Interim'), ('finalised', 'Finalised')],
                    default='interim', max_length=16)),
                ('deceased_name', models.CharField(blank=True, max_length=255)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('account_date', models.DateField(blank=True, null=True)),
                ('prepared_by_name', models.CharField(
                    default='ANP Solicitors', max_length=255)),
                ('prepared_by_address', models.TextField(
                    default=backend.models.DEFAULT_PREPARED_BY_ADDRESS)),
                ('inheritance_tax', models.DecimalField(
                    decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('will_clause_text', models.TextField(blank=True)),
                ('distribution_notes', models.TextField(blank=True)),
                ('acknowledgement_text', models.TextField(
                    default=backend.models.DEFAULT_ACKNOWLEDGEMENT_TEXT)),
                ('use_manual_totals', models.BooleanField(default=False)),
                ('manual_gross_estate', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_total_debts', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_net_estate', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_balance_for_distribution', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finance_snapshot', models.JSONField(blank=True, null=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalised_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='estate_accounts_finalised',
                    to=settings.AUTH_USER_MODEL)),
                ('matter', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='estate_account', to='backend.wip')),
            ],
        ),
        migrations.CreateModel(
            name='EstateAccountDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('share_fraction', models.CharField(blank=True, max_length=32)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_description', models.CharField(blank=True, max_length=255)),
                ('adjustment_amount', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL)),
                ('estate_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='distributions', to='backend.estateaccount')),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='EstateAccountFinanceLineOverride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[
                    ('slip', 'Payment slip'),
                    ('green_slip', 'Green slip'),
                    ('invoice', 'Invoice'),
                    ('credit_note', 'Credit note'),
                ], max_length=16)),
                ('source_id', models.PositiveIntegerField()),
                ('is_excluded', models.BooleanField(default=False)),
                ('date_override', models.DateField(blank=True, null=True)),
                ('description_override', models.CharField(blank=True, max_length=500)),
                ('amount_override', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('section_override', models.CharField(
                    blank=True, choices=[('asset', 'Asset'), ('debt', 'Debt')],
                    max_length=8, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('estate_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='finance_overrides', to='backend.estateaccount')),
            ],
            options={'unique_together': {('estate_account', 'source_type', 'source_id')}},
        ),
        migrations.CreateModel(
            name='EstateAccountManualEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(
                    choices=[('asset', 'Asset'), ('debt', 'Debt')], max_length=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_pending', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL)),
                ('estate_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='manual_entries', to='backend.estateaccount')),
            ],
            options={'ordering': ['sort_order', 'date', 'id']},
        ),
        migrations.CreateModel(
            name='EstateAccountSigner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_address', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('estate_account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signers', to='backend.estateaccount')),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
    ]
