# Generated by Django 5.1.4 on 2026-06-01

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_estate_account_distribution_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(
                    choices=[('draft', 'Draft'), ('finalised', 'Finalised')],
                    default='draft', max_length=16)),
                ('transaction_type', models.CharField(
                    choices=[('sale', 'Sale'), ('purchase', 'Purchase')],
                    default='sale', max_length=16)),
                ('completion_monies', models.DecimalField(
                    decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('property_address', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('prepared_by_name', models.CharField(
                    default='ANP Solicitors', max_length=255)),
                ('prepared_by_address', models.TextField(
                    default=backend.models.DEFAULT_PREPARED_BY_ADDRESS)),
                ('notes', models.TextField(blank=True)),
                ('finance_snapshot', models.JSONField(blank=True, null=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalised_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='completion_statements_finalised',
                    to=settings.AUTH_USER_MODEL)),
                ('matter', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='completion_statement', to='backend.wip')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionStatementFinanceLineOverride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[
                    ('slip', 'Payment slip'),
                    ('green_slip', 'Green slip'),
                    ('invoice', 'Invoice'),
                    ('credit_note', 'Credit note'),
                ], max_length=16)),
                ('source_id', models.PositiveIntegerField()),
                ('is_excluded', models.BooleanField(default=False)),
                ('date_override', models.DateField(blank=True, null=True)),
                ('description_override', models.CharField(blank=True, max_length=500)),
                ('amount_override', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direction_override', models.CharField(
                    blank=True, choices=[('add', 'Add'), ('less', 'Less')],
                    max_length=8, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('completion_statement', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='finance_overrides',
                    to='backend.completionstatement')),
            ],
            options={
                'unique_together': {
                    ('completion_statement', 'source_type', 'source_id'),
                },
            },
        ),
        migrations.CreateModel(
            name='CompletionStatementManualEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(
                    choices=[('add', 'Add'), ('less', 'Less')], max_length=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_pending', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL)),
                ('completion_statement', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='manual_entries',
                    to='backend.completionstatement')),
            ],
            options={'ordering': ['sort_order', 'date', 'id']},
        ),
    ]
