# Generated by Django 5.1.4 on 2026-06-02 10:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_completion_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionstatement',
            name='is_leasehold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completionstatementmanualentry',
            name='is_system_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompletionStatementApportionment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('rent', 'Rent'), ('service_charge', 'Service charge'), ('ground_rent', 'Ground rent'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('paid_in_advance', models.BooleanField(default=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('seller_days', models.PositiveIntegerField(default=0)),
                ('buyer_days', models.PositiveIntegerField(default=0)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('direction', models.CharField(choices=[('add', 'Add'), ('less', 'Less')], max_length=8)),
                ('sort_order', models.IntegerField(default=0)),
                ('completion_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apportionments', to='backend.completionstatement')),
                ('linked_manual_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apportionment_link', to='backend.completionstatementmanualentry')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompletionStatementMortgageRedemption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lender_name', models.CharField(blank=True, max_length=255)),
                ('loan_account_ref', models.CharField(blank=True, max_length=100)),
                ('redemption_figure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('redemption_statement_date', models.DateField(blank=True, null=True)),
                ('daily_interest_amount', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('calculated_days', models.PositiveIntegerField(default=0)),
                ('calculated_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('completion_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_redemption', to='backend.completionstatement')),
                ('linked_manual_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_redemption_link', to='backend.completionstatementmanualentry')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionStatementProceedsDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payee_name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('share_mode', models.CharField(choices=[('fraction', 'Fraction'), ('percent', 'Percent'), ('fixed', 'Fixed amount'), ('remainder', 'Remainder')], default='fraction', max_length=16)),
                ('share_value', models.CharField(blank=True, max_length=32)),
                ('projected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('penny_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('completion_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceeds_distributions', to='backend.completionstatement')),
                ('linked_manual_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proceeds_distribution_link', to='backend.completionstatementmanualentry')),
                ('linked_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proceeds_distribution_links', to='backend.pmtsslips')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompletionStatementScheduledPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payee_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('add', 'Add'), ('less', 'Less')], max_length=8)),
                ('ledger_account', models.CharField(choices=[('C', 'Client account'), ('O', 'Office account')], default='C', max_length=1)),
                ('projected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('slip_created', 'Slip created'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('source_kind', models.CharField(choices=[('manual', 'Manual'), ('mortgage', 'Mortgage redemption'), ('apportionment', 'Apportionment'), ('distribution', 'Distribution'), ('main_line', 'Main line')], default='manual', max_length=16)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('completion_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments', to='backend.completionstatement')),
                ('linked_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_payment_links', to='backend.pmtsslips')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('completion_statement', 'source_kind', 'source_id')},
            },
        ),
    ]
