# Generated by Django 5.1.4 on 2026-06-10 11:29

from django.db import migrations, models


def copy_client2_to_additional(apps, schema_editor):
    """Move every matter's secondary client (client2) into the new
    additional_clients M2M so no client association is lost when the
    client2 column is dropped."""
    WIP = apps.get_model('backend', 'WIP')
    for wip in WIP.objects.exclude(client2__isnull=True).iterator():
        # Never duplicate the primary client into the additional list.
        if wip.client2_id and wip.client2_id != wip.client1_id:
            wip.additional_clients.add(wip.client2_id)


def restore_client2_from_additional(apps, schema_editor):
    """Best-effort reverse: put the first additional client back into
    client2. Matters with more than one additional client cannot be fully
    restored to the old two-slot model, so only the first is moved back."""
    WIP = apps.get_model('backend', 'WIP')
    for wip in WIP.objects.iterator():
        first_additional = wip.additional_clients.order_by('id').first()
        if first_additional is not None:
            wip.client2_id = first_additional.id
            wip.save(update_fields=['client2'])


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_invoices_is_matter_final_invoice'),
    ]

    operations = [
        # 1. Create the new M2M before touching client2 so the data copy
        #    below has somewhere to land.
        migrations.AddField(
            model_name='wip',
            name='additional_clients',
            field=models.ManyToManyField(blank=True, related_name='additional_client_wips', to='backend.clientcontactdetails'),
        ),
        # 2. Copy existing client2 associations into additional_clients.
        migrations.RunPython(copy_client2_to_additional, restore_client2_from_additional),
        # 3. Only now drop client2 and the unused per-matter compliance flags
        #    (compliance is tracked on ClientContactDetails).
        migrations.RemoveField(
            model_name='wip',
            name='client2',
        ),
        migrations.RemoveField(
            model_name='wip',
            name='ncba_client1',
        ),
        migrations.RemoveField(
            model_name='wip',
            name='ncba_client2',
        ),
        migrations.RemoveField(
            model_name='wip',
            name='terms_of_engagement_client1',
        ),
        migrations.RemoveField(
            model_name='wip',
            name='terms_of_engagement_client2',
        ),
    ]
