# Generated by Django 5.1.4 on 2026-06-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_nextwork_is_admin_pool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GranolaConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, default='', help_text='Central Granola API key (Settings → Connectors in Granola). Leave blank to use the GRANOLA_API_KEY environment variable.', max_length=255)),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for the scheduled Granola sync.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.TextField(blank=True, default='', help_text='Outcome of the most recent sync run.')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granola_config_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Granola configuration',
                'verbose_name_plural': 'Granola configuration',
            },
        ),
        migrations.CreateModel(
            name='GranolaImportedNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('granola_note_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('summary_md', models.TextField(blank=True, default='', help_text='Raw Markdown summary from Granola.')),
                ('summary_html', models.TextField(blank=True, default='', help_text='Sanitised HTML rendered from the Markdown summary.')),
                ('transcript', models.TextField(blank=True, default='', help_text='Plain-text transcript from Granola.')),
                ('transcript_json', models.JSONField(blank=True, help_text='Structured per-utterance transcript as returned by Granola.', null=True)),
                ('meeting_start', models.DateTimeField(blank=True, null=True)),
                ('meeting_end', models.DateTimeField(blank=True, null=True)),
                ('note_created_at', models.DateTimeField(blank=True, null=True)),
                ('owner_email', models.EmailField(blank=True, default='', help_text='Email of the Granola note owner.', max_length=254)),
                ('parsed_file_number', models.CharField(blank=True, default='', max_length=20)),
                ('parsed_is_charged', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('created', 'Attendance note created'), ('ignored', 'Ignored'), ('error', 'Error')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granola_source', to='backend.matterattendancenotes')),
                ('matched_fee_earner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granola_notes', to=settings.AUTH_USER_MODEL)),
                ('matched_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granola_notes', to='backend.wip')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granola_notes_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_start', '-timestamp'],
            },
        ),
    ]
