# Generated by Django 5.1.4 on 2026-06-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_granolaconfig_granolaimportednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='granolaconfig',
            name='attendance_folder',
            field=models.CharField(blank=True, default='Attendance Note', help_text='Name of the shared Granola folder whose notes become matter attendance notes.', max_length=255),
        ),
        migrations.AddField(
            model_name='granolaconfig',
            name='free30_folder',
            field=models.CharField(blank=True, default='Free 30 min', help_text='Name of the shared Granola folder whose notes become Free 30 minute meeting records.', max_length=255),
        ),
        migrations.AddField(
            model_name='granolaimportednote',
            name='free30_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granola_source', to='backend.free30mins'),
        ),
        migrations.AddField(
            model_name='granolaimportednote',
            name='note_type',
            field=models.CharField(choices=[('attendance', 'Attendance note'), ('free30', 'Free 30 minutes')], default='attendance', max_length=16),
        ),
        migrations.AlterField(
            model_name='granolaimportednote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('created', 'Record created'), ('ignored', 'Ignored'), ('error', 'Error')], default='pending', max_length=16),
        ),
    ]
