# Generated by Django 5.1.4 on 2026-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_granolaconfig_attendance_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='granolaconfig',
            name='last_full_scan_at',
            field=models.DateTimeField(blank=True, help_text='When the last complete folder re-scan ran (catches notes added to a folder without bumping their updated_at).', null=True),
        ),
    ]
