# Generated by Django 5.1.4 on 2026-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_granolaconfig_last_full_scan_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='granolaconfig',
            name='start_date',
            field=models.DateField(blank=True, help_text='The scheduled sync stays dormant until this date (manual "Sync now" still works). Leave blank to start immediately.', null=True),
        ),
    ]
