# Generated by Django 5.1.4 on 2026-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_backfill_bundle_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersidedetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='othersidedetails',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
