# Generated by Django 5.1.4 on 2026-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_alter_othersidedetails_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matteremails',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=4096, null=True),
        ),
    ]
