# Generated by Django 5.1.4 on 2026-09-03 15:28

from django.db import migrations
from django.db.models import F


def mark_existing_assessments_signed(apps, schema_editor):
    """Existing assessments predate the sign-off workflow: treat them as
    signed off by their recorded signer so dashboards don't flood with
    historical 'awaiting sign-off' entries."""
    RiskAssessment = apps.get_model('backend', 'RiskAssessment')
    RiskAssessment.objects.update(
        signoff_status='signed',
        signed_off_by=F('due_diligence_signed_by'),
        signed_off_at=F('timestamp'),
    )


def unmark(apps, schema_editor):
    RiskAssessment = apps.get_model('backend', 'RiskAssessment')
    RiskAssessment.objects.update(
        signoff_status='awaiting',
        signed_off_by=None,
        signed_off_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_riskassessment_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(mark_existing_assessments_signed, unmark),
    ]
