# Generated by Django 5.1.4 on 2026-06-16 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_set_granola_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('collecting', 'Collecting'), ('ready_for_review', 'Ready for review'), ('converted', 'Converted')], default='invited', max_length=20)),
                ('portal_submission_id', models.CharField(blank=True, default='', max_length=64)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_created_by', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings', to='backend.wip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('proof_id', 'Proof of ID'), ('proof_address', 'Proof of address'), ('selfie_id', 'Selfie with ID'), ('source_of_funds', 'Source of funds declaration'), ('pep', 'PEP declaration')], max_length=20)),
                ('sharepoint_item_id', models.CharField(blank=True, default='', max_length=128)),
                ('kyc_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_items_accepted', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.onboarding')),
            ],
            options={
                'unique_together': {('onboarding', 'item_type')},
            },
        ),
    ]
