# Generated by Django 5.1.4 on 2026-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_onboarding_onboardingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionstatementscheduledpayment',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='completionstatementscheduledpayment',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='completionstatementscheduledpayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='completionstatementscheduledpayment',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='completionstatementscheduledpayment',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
