# Generated by Django 5.1.4 on 2026-06-16 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_completionstatementscheduledpayment_bank_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('searched_name', models.CharField(max_length=255)),
                ('searched_dob', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('clear', 'No conflict found'), ('potential_conflict', 'Potential conflict found')], default='clear', max_length=20)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledgement_note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks', to='backend.clientcontactdetails')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('wip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks', to='backend.wip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
