# Generated by Django 5.1.4 on 2026-06-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_conflictcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictcheck',
            name='onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflict_checks', to='backend.onboarding'),
        ),
    ]
