# Generated by Django 5.1.4 on 2026-06-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_conflictcheck_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='matter',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='county',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='OnboardingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('matter_description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('ready_for_review', 'Ready for review'), ('converted', 'Converted')], default='collecting', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_groups_created', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_groups', to='backend.wip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='onboarding',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='backend.onboardinggroup'),
        ),
    ]
