# Generated by Django 5.1.4 on 2026-06-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_remove_onboarding_matter_onboarding_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_member', to='backend.clientcontactdetails'),
        ),
    ]
