# Generated by Django 5.1.4 on 2026-06-16 15:33

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_onboarding_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingitem',
            name='file',
            field=models.FileField(blank=True, null=True, storage=backend.models.onboarding_doc_storage, upload_to=backend.models.onboarding_document_upload_path),
        ),
    ]
