# Generated by Django 5.1.4 on 2026-06-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_onboardingitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingitem',
            name='item_type',
            field=models.CharField(choices=[('proof_id', 'Proof of ID'), ('proof_address', 'Proof of address'), ('selfie_id', 'Selfie with ID'), ('source_of_funds', 'Source of funds declaration'), ('pep', 'PEP declaration'), ('terms_of_engagement', 'Terms of engagement')], max_length=20),
        ),
    ]
