# Generated by Django 5.1.4 on 2026-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_alter_onboardingitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='invite_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='portal_invite_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='portal_invite_link',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
