# Generated by Django 5.1.4 on 2026-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_onboarding_invite_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersidedetails',
            name='date_of_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othersidedetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othersidedetails',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
