# Generated by Django 5.1.4 on 2026-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_othersidedetails_date_of_incorporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='required_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
