# Generated by Django 5.1.4 on 2026-07-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_onboarding_required_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingitem',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='onboardingitem',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='onboardingitem',
            name='kyc_accepted',
        ),
    ]
