# Generated by Django 5.1.4 on 2026-07-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_remove_onboardingitem_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingitem',
            name='document_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
