# Generated by Django 5.1.4 on 2026-09-14 14:48

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_onboardingitem_document_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveyancingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('purchase_sale', 'Purchase & sale'), ('remortgage', 'Remortgage'), ('transfer', 'Transfer of equity')], default='', max_length=20)),
                ('property_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_address', models.CharField(blank=True, default='', max_length=500)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conveyancing', to='backend.wip')),
            ],
        ),
        migrations.CreateModel(
            name='MatterClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(default=False)),
                ('terms_of_engagement_signed', models.BooleanField(default=False)),
                ('terms_of_engagement_on', models.DateField(blank=True, null=True)),
                ('terms_sent_on', models.DateField(blank=True, null=True)),
                ('terms_received_on', models.DateField(blank=True, null=True)),
                ('ncba_required', models.BooleanField(default=True)),
                ('ncba_signed', models.BooleanField(default=False)),
                ('ncba_on', models.DateField(blank=True, null=True)),
                ('ncba_sent_on', models.DateField(blank=True, null=True)),
                ('ncba_received_on', models.DateField(blank=True, null=True)),
                ('source_of_funds_signed', models.BooleanField(default=False)),
                ('source_of_funds_on', models.DateField(blank=True, null=True)),
                ('source_of_funds_details', models.CharField(blank=True, default='', max_length=255)),
                ('pep_signed', models.BooleanField(default=False)),
                ('pep_on', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('captured', 'Captured for this matter'), ('reconstructed', 'Reconstructed from matter evidence'), ('carried_over', 'Carried over from the client record')], default='captured', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_links', to='backend.clientcontactdetails')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_clients', to='backend.wip')),
                ('ncba_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pep_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_of_funds_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('terms_of_engagement_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('matter', 'client')},
            },
        ),
        migrations.CreateModel(
            name='MatterClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('terms', 'Terms of engagement'), ('ncba', 'NCBA'), ('source_of_funds', 'Source of funds'), ('pep', 'PEP declaration'), ('aml_id_check', 'AML / ID check'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(storage=backend.models.matter_client_doc_storage, upload_to=backend.models.matter_client_document_upload_path)),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('document_reference', models.CharField(blank=True, default='', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('matter_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='backend.matterclient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
