# Generated by Django 5.1.4 on 2026-09-14 16:17

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_backfill_matter_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientkeydocument',
            name='file',
            field=models.FileField(blank=True, null=True, storage=backend.models.client_key_doc_storage, upload_to=backend.models.client_key_document_upload_path),
        ),
    ]
