# Generated by Django 5.1.4 on 2026-10-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_redate_completed_tasks'),
        ('backend', '0086_wip_ncba_required_and_more'),
    ]

    operations = [
    ]
