# Generated by Django 5.1.4 on 2026-10-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_merge_main_into_matter_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wip',
            name='actual_destruction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wip',
            name='brought_down_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wip',
            name='latest_destruction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wip',
            name='paying_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paying_party_wip', to='backend.authorisedparties'),
        ),
    ]
